### PR TITLE
WAZO-3001: `agentd` publish to wazo headers

### PR DESCRIPTION
**Pull request by ja0x**
Depends-On: https://github.com/wazo-platform/wazo-amid-client/pull/10

### CODE REVIEW

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
grepping for `routing` leave some of helpers, please remove them if not used

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
