### PR TITLE
Wazo 2527 agent blf api

### PR DESCRIPTION
**Pull request by pc-m**
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/139
Depends-On: https://github.com/wazo-platform/wazo-auth-keys/pull/54
Depends-On: https://github.com/wazo-platform/xivo-test-helpers/pull/56

### CODE REVIEW

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
> Build failed.
> 
>     * [tox-linters ](https://zuul.wazo.community/zuul/t/local/build/190223ee85734897ab349e8481976195) : FAILURE in 3m 10s
> 
>     * [wazo-tox-py37 ](https://zuul.wazo.community/zuul/t/local/build/d7252fd3112a4c0ba45d407a495de6ce) : SUCCESS in 3m 38s
> 
>     * [wazo-tox-integration ](https://zuul.wazo.community/zuul/t/local/build/8168147ce41d49bab213e41005df7052) : FAILURE in 7m 29s
> 
>     * [debian-packaging ](https://zuul.wazo.community/zuul/t/local/build/7e2b76d1451a4086b739810094217e70) : SUCCESS in 5m 19s

It seems like something is missing in the amid mock. Locally, I get:

```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/src/wazo-agentd/wazo_agentd/http.py", line 80, in aux
    return fun(*args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/xivo/auth_verifier.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/src/wazo-agentd/wazo_agentd/http.py", line 181, in post
    user_uuid, body['line_id'], tenant_uuids=tenant_uuids
  File "/usr/src/wazo-agentd/wazo_agentd/service/proxy.py", line 48, in login_user_agent
    user_uuid, line_id, tenant_uuids=tenant_uuids
  File "/usr/src/wazo-agentd/wazo_agentd/service/handler/login.py", line 51, in handle_login_user_agent
    self._login_manager.login_user_agent(agent, user_uuid, line_id)
  File "/usr/src/wazo-agentd/wazo_agentd/service/manager/login.py", line 34, in login_user_agent
    self._login_action.login_agent_on_line(agent, line_id)
  File "/usr/src/wazo-agentd/wazo_agentd/service/action/login.py", line 51, in login_agent_on_line
    self._do_login(agent, extension, context, interface, state_interface)
  File "/usr/src/wazo-agentd/wazo_agentd/service/action/login.py", line 57, in _do_login
    self._update_blf(agent)
  File "/usr/src/wazo-agentd/wazo_agentd/service/action/login.py", line 113, in _update_blf
    self._blf_manager.set_user_blf(user_id, 'agentstaticlogin', 'INUSE', '*{}'.format(agent.id))
  File "/usr/src/wazo-agentd/wazo_agentd/service/manager/blf.py", line 34, in set_user_blf
    result = self._amid_client.command(cli_command)
  File "/opt/venv/lib/python3.7/site-packages/wazo_amid_client/commands/command.py", line 18, in __call__
    self.raise_from_response(r)
  File "/opt/venv/lib/python3.7/site-packages/wazo_amid_client/command.py", line 22, in raise_from_response
    RESTCommand.raise_from_response(response)
  File "/opt/venv/lib/python3.7/site-packages/wazo_lib_rest_client/command.py", line 25, in raise_from_response
    response.raise_for_status()
  File "/opt/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://amid:9491/1.0/action/Command
2021-09-22 14:33:49,232 [1] (INFO) (flask.app): response: (172.20.0.1) POST http://127.0.0.1:32773/1.0/users/me/agents/login 500
2021-09-22 14:33:49,232 [1] (DEBUG) (flask.app): response body: {"message": "Internal Server Error"}
```

**Review by bloom1 — CHANGES_REQUESTED** [review]
> Build failed.
> 
>     * [tox-linters ](https://zuul.wazo.community/zuul/t/local/build/190223ee85734897ab349e8481976195) : FAILURE in 3m 10s
> 
>     * [wazo-tox-py37 ](https://zuul.wazo.community/zuul/t/local/build/d7252fd3112a4c0ba45d407a495de6ce) : SUCCESS in 3m 38s
> 
>     * [wazo-tox-integration ](https://zuul.wazo.community/zuul/t/local/build/8168147ce41d49bab213e41005df7052) : FAILURE in 7m 29s
> 
>     * [debian-packaging ](https://zuul.wazo.community/zuul/t/local/build/7e2b76d1451a4086b739810094217e70) : SUCCESS in 5m 19s

It seems like something is missing in the amid mock. Locally, I get:

```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/src/wazo-agentd/wazo_agentd/http.py", line 80, in aux
    return fun(*args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/xivo/auth_verifier.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/usr/src/wazo-agentd/wazo_agentd/http.py", line 181, in post
    user_uuid, body['line_id'], tenant_uuids=tenant_uuids
  File "/usr/src/wazo-agentd/wazo_agentd/service/proxy.py", line 48, in login_user_agent
    user_uuid, line_id, tenant_uuids=tenant_uuids
  File "/usr/src/wazo-agentd/wazo_agentd/service/handler/login.py", line 51, in handle_login_user_agent
    self._login_manager.login_user_agent(agent, user_uuid, line_id)
  File "/usr/src/wazo-agentd/wazo_agentd/service/manager/login.py", line 34, in login_user_agent
    self._login_action.login_agent_on_line(agent, line_id)
  File "/usr/src/wazo-agentd/wazo_agentd/service/action/login.py", line 51, in login_agent_on_line
    self._do_login(agent, extension, context, interface, state_interface)
  File "/usr/src/wazo-agentd/wazo_agentd/service/action/login.py", line 57, in _do_login
    self._update_blf(agent)
  File "/usr/src/wazo-agentd/wazo_agentd/service/action/login.py", line 113, in _update_blf
    self._blf_manager.set_user_blf(user_id, 'agentstaticlogin', 'INUSE', '*{}'.format(agent.id))
  File "/usr/src/wazo-agentd/wazo_agentd/service/manager/blf.py", line 34, in set_user_blf
    result = self._amid_client.command(cli_command)
  File "/opt/venv/lib/python3.7/site-packages/wazo_amid_client/commands/command.py", line 18, in __call__
    self.raise_from_response(r)
  File "/opt/venv/lib/python3.7/site-packages/wazo_amid_client/command.py", line 22, in raise_from_response
    RESTCommand.raise_from_response(response)
  File "/opt/venv/lib/python3.7/site-packages/wazo_lib_rest_client/command.py", line 25, in raise_from_response
    response.raise_for_status()
  File "/opt/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://amid:9491/1.0/action/Command
2021-09-22 14:33:49,232 [1] (INFO) (flask.app): response: (172.20.0.1) POST http://127.0.0.1:32773/1.0/users/me/agents/login 500
2021-09-22 14:33:49,232 [1] (DEBUG) (flask.app): response body: {"message": "Internal Server Error"}
```

**Comment by pc-m** [comment]
recheck

**Review by bloom1 — APPROVED** [review]

**Pull request merged**
